// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://slfxuomampsfdosxtatr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNsZnh1b21hbXBzZmRvc3h0YXRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA2OTgzMjQsImV4cCI6MjA3NjI3NDMyNH0.ism7Rol18IIqkN1hpe8BXPl2dtYonosSf3zR7TH4r5Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);